Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

EndOfLine:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Exclude:
    - test/factories/hosting.rb

Style/RedundantBegin:
  Enabled: false
